import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/wrapper/LenisScroll";
import Background from "@/components/Background";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Aauraa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} font-sans antialiased`}>
        <LenisProvider>
         <Background>
   {children}

         </Background>
  
     

        </LenisProvider>
      </body>
    </html>
  );
}
